FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY . .

RUN dotnet restore Maraudr.Stock.Endpoints/Maraudr.Stock.Endpoints.csproj

WORKDIR /src/Maraudr.Stock.Endpoints
RUN dotnet build Maraudr.Stock.Endpoints.csproj -c Debug -o /app/build

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app

ENV ASPNETCORE_ENVIRONMENT=Development

COPY --from=build /app/build .

EXPOSE 8080

ENTRYPOINT ["dotnet", "Maraudr.Stock.Endpoints.dll"]
